# Generated by Django 5.2.2 on 2025-08-07 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boutique', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_suivi', models.CharField(blank=True, max_length=100, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('longueur_cm', models.IntegerField(blank=True, null=True)),
                ('largeur_cm', models.IntegerField(blank=True, null=True)),
                ('hauteur_cm', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('valeur_declaree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=100)),
                ('date_depot', models.DateField(blank=True, null=True)),
                ('statut_courant', models.CharField(choices=[('declare', 'Déclaré'), ('receptionne', 'Réceptionné'), ('en_attente', "En attente d'expédition"), ('expedie', 'Expédié'), ('livre', 'Livré'), ('probleme', 'Problème')], default='declare', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_colis', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('declare', 'Déclaré'), ('receptionne', 'Réceptionné'), ('en_attente', "En attente d'expédition"), ('expedie', 'Expédié'), ('livre', 'Livré'), ('probleme', 'Problème')], max_length=50)),
                ('emplacement', models.CharField(max_length=255)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_suivi', to='api.colis')),
            ],
            options={
                'verbose_name': 'Historique de Suivi',
                'verbose_name_plural': 'Historiques de Suivi',
                'ordering': ['date_heure'],
            },
        ),
    ]
