# Generated by Django 5.2.2 on 2025-06-09 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('adresse', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('longueur_cm', models.IntegerField()),
                ('largeur_cm', models.IntegerField()),
                ('hauteur_cm', models.IntegerField()),
                ('description', models.TextField()),
                ('valeur_declaree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=100)),
                ('date_depot', models.DateField()),
                ('statut_courant', models.CharField(choices=[('receptionne', 'Réceptionné'), ('en_attente', "En attente d'expédition"), ('expedie', 'Expédié'), ('livre', 'Livré'), ('probleme', 'Problème')], default='receptionne', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='api.client')),
            ],
        ),
    ]
